### ISSUE TITLE
NMods does not support arm64

### ISSUE THREAD

**Issue by listerily** [listerily/ModdedBE#3]
Due to substrate doesn't support arm64,NMods does not support arm64 temporarily. But ModdedBE could still launch game.

**Comment by timscriptov** [comment]
Don't use substrate. Use https://github.com/iqiyi/xHook

**Comment by timscriptov** [comment]
It work for Minecraft 1.16 arm 32 and 64...

**Comment by listerily** [comment]
> It work for Minecraft 1.16 arm 32 and 64...
I'll have a try.

**Comment by TripleCamera** [comment]
> > It work for Minecraft 1.16 arm 32 and 64...
> > I'll have a try.

It seems like PLT hook is designed for hooking **cross-library** calls???

**Comment by TimScriptov** [comment]
@TripleCamera Sorry, I don't understand 😅

**Comment by TimScriptov** [comment]
@TripleCamera ![](https://i.imgur.com/Yh6fIMn.png)

**Comment by TimScriptov** [comment]
_ZN5Biome11getSkyColorEf

**Comment by Lamfi** [comment]
use xHook it works much better than Substrate and work with ARM64. And has its own debug in LogCat usage example:
void (*onDimension)(void*);
void onDimension_hook(void* a){

return normalTick(a);
}
//Load lib 
xhook_register(".*/libminecraftpe\\.so$","_ZN13MinecraftGame18onDimensionChangedEv",(void*) &onDimension_hook, (void**) &onDimension);
xhook_refresh(1);
xhook_enable_debug(1); //Debug to logcat with tag xhook

**Comment by TimScriptov** [comment]
https://github.com/TimScriptov/ModdedPE/blob/ModdedPE-JAVA/app/src/main/cpp/xhook-skycolor/main.cpp
