### ISSUE TITLE
Dump headers

### ISSUE THREAD

**Issue by timscriptov** [listerily/ModdedBE#6]
How can i get attribute for class Actor from shared library?

Example:
```
class Actor {
int x,y,z;
}
```

Example 2:
```
class Color {
float red,green,blue <- how to debug from shared library libminecraftpe
}
```

**Comment by listerily** [comment]
Dumping attributes by disassemblers is impossible. When compiling, C/C++ compilers will ignore the attributes' name and replace them with the address offsets.
For example:

```
struct Actor{ int x,y,z; };

Actor myActor;
myActor.y = 0;
```

Will be translated into:
```
struct Actor{ int x,y,z; };

Actor myActor;
*((void*)(&myActor) + sizeof(int)) /* size of the attributes before attribute "x" */ = 0;
```
As a result, compiling loses the name of attributes and leaves address offsets only. We can only get to know where the attribute locates, but it's impossible for us to know the original name of the attributes.
